name: jam

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    container_name: jam-server
    ports:
      - "8787:8787"
    env_file:
      - ./server/.env

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: jam-client
    ports:
      - "3000:3000"
